# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  newman: postman/newman@1.0.0
  win: circleci/windows@5.0
  node: circleci/node@5.0.3

commands:
  install-node:
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
  
  install-npm:
    steps:
      - checkout
      - run: npm install npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          
      - run:
          name: Newman setup  
          command: |
            npm install -g newman 

      - run: npm list -g


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout

      - run: |
             npm install -g newman
             echo " newman was set up"
             newman --version
             
      - run:
          name: Day0_Collection
          command: 
            echo "Run Day0 Collection"

      - newman/newman-run:
          collection: ./'Day0 Pre-requisites'/"Day 00- Pre-requisites.postman_collection.json"
          
      - run:
          name: Day1_Collection
          command: 
            echo "Run Day1 Collection"

      - newman/newman-run:
          collection: ./'Day1 Fork a collection'/"Day 01- Fork a collection.postman_collection.json"
                    
      - run:
          name: Day2_Collection
          command: 
            echo "Run Day2 Collection"

      - newman/newman-run:
          collection: ./'Day2 Collections and environments'/02Collections_and_environments.postman_collection.json
          environment: ./'Day2 Collections and environments'/'Day 02 Environment.postman_environment.json'

      - run:
          name: Day3_Collection
          command: 
            echo "Run Day3 Collection"

      - newman/newman-run:
          collection: ./'Day3 Add request details'/03Add_Request_details.postman_collection.json
          environment: ./'Day3 Add request details'/'Day 03 Environment.postman_environment.json'

      - run:
          name: Day4_Collection
          command: 
            echo "Run Day4 Collection"

      - newman/newman-run:
          collection: ./'Day4 Authorization'/04Authorization.postman_collection.json
          environment: ./'Day4 Authorization'/'Day 04 Environment.postman_environment.json'

      - run:
          name: Day5_Collection
          command: 
            echo "Run Day5 Collection"

      - newman/newman-run:
          environment: ./'Day5 Variables'/'Day 05 Environment.postman_environment.json'
          collection: ./'Day5 Variables'/05Variables.postman_collection.json

      - run:
          name: Day7_Collection
          command: 
            echo "Run Day7 Collection"

      - newman/newman-run:
          collection: ./Day7Debugging/"Day 07- Debugging.postman_collection.json"
          environment: ./Day7Debugging/'Day 07 Environment.postman_environment.json'

      - run:
          name: Day8_Collection
          command: 
            echo "Run Day8 Collection"

      - newman/newman-run:
          collection: ./'Day8 Run a collection'/08Run_a_collection.postman_collection.json
          environment: ./'Day8 Run a collection'/'Day 08 Environment.postman_environment.json'

      - run:
          name: Day9_Collection
          command: 
            echo "Run Day9 Collection"

      - newman/newman-run:
          collection: ./'Day9 Scripting'/09Scripting.postman_collection.json
          environment: ./'Day9 Scripting'/'Day 09 Environment.postman_environment.json'

      - run:
          name: Day10_Collection
          command: 
            echo "Run Day10 Collection"

      - newman/newman-run:
          collection: ./'Day10 Mock services'/10Mock_services.postman_collection.json
          environment: ./'Day10 Mock services'/'Day 10 Environment.postman_environment.json'
          
      - run:
          name: Day11_Collection
          command: 
            echo "Run Day11 Collection"

      - newman/newman-run:
          collection: ./'Day11 Monitoring'/11Monitoring.postman_collection.json
          environment: ./'Day11 Monitoring'/'Day 11 Environment.postman_environment.json

      - run:
          name: Day12_Collection
          command: 
            echo "Run Day12 Collection"

      - newman/newman-run:
          collection: ./'Day12 Postman API'/'12Postman API.postman_collection.json'
          environment: ./'Day12 Postman API'/12Environment.postman_environment.json
          
      - newman/newman-run:
          collection: ./'Day13 Newman'/13Newman.postman_collection.json
          environment: ./'Day13 Newman'/'Day 13 Environment.postman_environment.json'
          
      - run:
          name: Day17_Collection
          command: 
            echo "Run Day17 Collection"

      - newman/newman-run:
          collection: ./'Day17 Visualizations'/17Visualizations.postman_collection.json
          environment: ./'Day17 Visualizations'/17Environment.postman_environment.json

      - run:
          name: Day18_Collection
          command: 
            echo "Run Day18 Collection"

      - newman/newman-run:
          collection: ./'Day18 APISpecifications'/18APISpecifications.postman_collection.json
          environment: ./'Day18 APISpecifications'/'Postman API Env Day 18.postman_environment.json'

      - run:
          name: Day20_Collection
          command: 
            echo "Run Day20 Collection"

      - newman/newman-run:
          collection: ./'Day20 Documentation'/20Documentation.postman_collection.json
          environment: ./'Day20 Documentation'/'Postman API Env Day 20.postman_environment.json'
          
      - run:
          name: Day24_Collection
          command: 
            echo "Run Day24 Collection"

      - newman/newman-run:
          collection: ./'Day24 Using libraries'/'24Using libraries.postman_collection.json'
          environment: ./'Day24 Using libraries'/'Postman API Env Day 24.postman_environment.json'

      - run:
          name: Day25_Collection
          command: 
            echo "Run Day25 Collection"

      - newman/newman-run:
          collection: ./'Day25 Dynamic request bodies'/'25Dynamic request bodies.postman_collection.json'
          environment: ./'Day25 Dynamic request bodies'/'Postman API Env Day 25.postman_environment.json'
          
      - run:
          name: Day26_Collection
          command: 
            echo "Run Day26 Collection"

      - newman/newman-run:
          collection: ./'Day26 Parse HTML response'/26Parse_HTML_response.postman_collection.json
          environment: ./'Day26 Parse HTML response'/26Environment.postman_environment.json

      - run:
          name: Day27_Collection
          command: 
            echo "Run Day27 Collection"

      - newman/newman-run:
          collection: ./'Day27 Scenario testing'/27Scenario_testing.postman_collection.json
          environment: ./'Day27 Scenario testing'/Postman API Env Day 27.postman_environment.json'

  build-newman:
    executor: node/default
    working_directory: /home/circleci/project/
    steps:
      - checkout
      - node/install-packages:
           pkg-manager: yarn

      # - run:
      #  command: yarn test
      #  name: Run tests
      # - run:
      #  command: yarn build
      #  name: Build app
      # - persist_to_workspace:
      #     root: ~/project
      #     paths:
      #       - .

  test:
    executor: node/default
    steps:
      - checkout
      - install-node
      #- install-npm
      - run: npm --version
      - restore_cache:
          key: newman--{{ checksum "package-lock.json" }}

  test-newman:
    executor: node/default
    steps:
      - checkout
      - run: |
             sudo npm install -g npm@latest
             echo "npm modules was installed"
             sudo npm install -g newman
             sudo npm install -g newman-reporter-htmlextra

             echo " newman was set up"
             newman --version
             ls -a .

      - run: |
              echo "Run the collection and the environment Day 00"
              echo "Let us look up files"
              cd ~/project

              newman run ./'Day0 Pre-requisites'/"Day 00- Pre-requisites.postman_collection.json"  -r cli, json
             
      - run: |
              echo "Run the collection and the environment Day 01"
              echo "Let us look up files"
              cd ~/project

              newman run ./'Day1 Fork a collection'/"Day 01- Fork a collection.postman_collection.json" -r cli, json
             
      - run: |
              echo "Run the collection and the environment Day 02"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day2 Collections and environments'/02Collections_and_environments.postman_collection.json -e ./'Day2 Collections and environments'/'Day 02 Environment.postman_environment.json' \
               -r cli, json
             
      - run: |
              echo "Run the collection and the environment Day 03"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day3 Add request details'/03Add_Request_details.postman_collection.json  -e ./'Day3 Add request details'/'Day 03 Environment.postman_environment.json' \
               -r cli, json

      - run: |
              echo "Run the collection and the environment Day 04"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day4 Authorization'/04Authorization.postman_collection.json  -e ./'Day4 Authorization'/'Day 04 Environment.postman_environment.json' \
               -r cli, json

      - run: |
              echo "Run the collection and the environment Day 05"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day5 Variables'/05Variables.postman_collection.json  -e ./'Day5 Variables'/'Day 05 Environment.postman_environment.json' \
               -r cli, json

      - run: |
              echo "Run the collection and the environment Day 07"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./Day7Debugging/"Day 07- Debugging.postman_collection.json" -e ./Day7Debugging/'Day 07 Environment.postman_environment.json' \
               -r cli, json
               
      - run: |
              echo "Run the collection and the environment Day 08"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day8 Run a collection'/08Run_a_collection.postman_collection.json -e ./'Day8 Run a collection'/'Day 08 Environment.postman_environment.json'  \
               -r cli, json

      - run: |
              echo "Run the collection and the environment Day 09"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day9 Scripting'/09Scripting.postman_collection.json -e ./'Day9 Scripting'/'Day 09 Environment.postman_environment.json'  \
               -r cli, json

      - run: |
              echo "Run the collection and the environment Day 10"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day10 Mock services'/10Mock_services.postman_collection.json -e ./'Day10 Mock services'/'Day 10 Environment.postman_environment.json' \
               -r cli, json

      - run: |
              echo "Run the collection and the environment Day 11"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day11 Monitoring'/11Monitoring.postman_collection.json -e ./'Day11 Monitoring'/'Day 11 Environment.postman_environment.json' \
               -r cli, json
               
      - run: |
              echo "Run the collection and the environment Day 12"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day12 Postman API'/'12Postman API.postman_collection.json' -e ./'Day12 Postman API'/'Postman API env.postman_environment.json' \
               -r cli, json

      - run: |
              echo "Run the collection and the environment Day 13"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day13 Newman'/13Newman.postman_collection.json -e ./'Day13 Newman'/'Day 13 Environment.postman_environment.json' \
               -r cli, json

      #- run: |
              #echo " Let us run Day 15"
              #echo "Let us look up files"
              #pwd

              #newman run Day15WritetoFile/"Day 15- Write to file.postman_collection.json" -e Day15WritetoFile/"Postman API Env Day 15.postman_environment.json" \
              #-r cli, json --working-dir /root/project -d Day15WritetoFile/script.js  -n 1 

      - run: |
              echo "Run the collection and the environment Day 17"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day17 Visualizations'/17Visualizations.postman_collection.json -e ./'Day17 Visualizations'/'Postman API Env Day 17.postman_environment.json' \
               -r cli, json

      - run: |
              echo "Run the collection and the environment Day 18"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day18 APISpecifications'/18APISpecifications.postman_collection.json -e ./'Day18 APISpecifications'/'Postman API Env Day 18.postman_environment.json' \
               -r cli, json
               
      - run: |
              echo "Run the collection and the environment Day 20"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day20 Documentation'/20Documentation.postman_collection.json -e ./'Day20 Documentation'/'Postman API Env Day 20.postman_environment.json' \
               -r cli, json
               
      - run: |
              echo "Run the collection and the environment Day 23"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run /.'Day23 Data files'/23Datafiles.postman_collection.json -e "/.'Day23 Data files'/'Postman API Env Day 23.postman_environment.json' \
               -r cli, json -d geoMap.csv -n 1

      - run: |
              echo "Run the collection and the environment Day 24"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day24 Using libraries'/'24Using libraries.postman_collection.json' -e ./'Day24 Using libraries'/'Postman API Env Day 24.postman_environment.json' \
               -r cli, json
               
      - run: |
              echo "Run the collection and the environment Day 25"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run  ./'Day25 Dynamic request bodies'/'25Dynamic request bodies.postman_collection.json' -e ./'Day25 Dynamic request bodies'/'Postman API Env Day 25.postman_environment.json' \
               -r cli, json

      - run: |
              echo "Run the collection and the environment Day 26"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day26 Parse HTML response'/26Parse_HTML_response.postman_collection.json -e ./'Day26 Parse HTML response'/26Environment.postman_environment.json \
               -r cli, json

      - run: |
              echo "Run the collection and the environment Day 27"
              echo "Let us look up files"
              echo "API token expiration date October 11 2024"
              cd ~/project

              newman run ./'Day27 Scenario testing'/27Scenario_testing.postman_collection.json -e ./'Day27 Scenario testing'/Postman API Env Day 27.postman_environment.json' \
               -r cli, json

              
  deploy:
    executor: win/server-2022
    steps:
      - checkout
      - run:
          name: Tag Git repo
          command: |
            git config --global user.email aymar.nahum@jecorde.com
            git config --global user.name  AymarN
            git tag -a "v0.1.0" -m "Release v0.1.0" 


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:

  I-30_Days_Of_Postman_Orb_Newman:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
             only: main
      - deploy:
          requires:
            - test 
          filters:
            branches:
              only: main

  II-30_Days_Of_Postman_Newman:
    jobs:
      - build-newman
      - test-newman:
          requires:
            - build-newman
          filters:
            branches:
             only: main
      - deploy:
          requires:
            - test-newman 
          filters:
            branches:
              only: main
